import { TopBar } from "../../components/common/TopBar";

const detailContent = {
  title: "대학생이라면 주목! 2024학년도 2학기 1차 국가장학금 신청하기",
  date: "2024. 6. 7",
  content: `<div class="tt_article_useless_p_margin contents_style"><p></p><figure class="imageblock alignCenter" data-ke-mobilestyle="widthOrigin" data-filename="1 표지.jpg" data-origin-width="1080" data-origin-height="1080"><span data-url="https://blog.kakaocdn.net/dn/bH4lQM/btsHQJg1seO/jRwqlmPSebLRUlKHG3f2d1/img.jpg" data-phocus="phocus"><img src="https://blog.kakaocdn.net/dn/bH4lQM/btsHQJg1seO/jRwqlmPSebLRUlKHG3f2d1/img.jpg" srcset="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&amp;fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbH4lQM%2FbtsHQJg1seO%2FjRwqlmPSebLRUlKHG3f2d1%2Fimg.jpg" onerror="this.onerror=null; this.src='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png'; this.srcset='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png';" data-filename="1 표지.jpg" data-origin-width="1080" data-origin-height="1080" data-phocus-index="0"></span></figure>
<figure class="imageblock alignCenter" data-ke-mobilestyle="widthOrigin" data-filename="2 배너.jpg" data-origin-width="1080" data-origin-height="400"><span data-url="https://blog.kakaocdn.net/dn/7SKiH/btsHPygv3xW/AUqVum1nDKiGSyqIWfT2JK/img.jpg" data-phocus="phocus"><img src="https://blog.kakaocdn.net/dn/7SKiH/btsHPygv3xW/AUqVum1nDKiGSyqIWfT2JK/img.jpg" srcset="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&amp;fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2F7SKiH%2FbtsHPygv3xW%2FAUqVum1nDKiGSyqIWfT2JK%2Fimg.jpg" onerror="this.onerror=null; this.src='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png'; this.srcset='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png';" data-filename="2 배너.jpg" data-origin-width="1080" data-origin-height="400" data-phocus-index="1"></span></figure>
<p></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';">대학교 재학생이라면 누구나 신청할 수 있는 2024학년도 2학기 1차 국가장학금 접수가 현재 진행 중입니다. 지난 5월 21일부터 오는 6월 20일 오후 18시까지 진행되는 1차 국가장학금은 나이와 관계없이 국내 대학에 재학 중인 재학생과 복학생, 신입생 및 편입생 등 모든 대학생이 신청 가능한데요. 특히 재학생은 반드시 1차에 신청해야 하므로 서둘러 신청 대상과 신청 방법을 참고해 기간에 늦지 않도록 신청해 보시기 바랍니다.</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';"><b><span style="color: rgb(0, 145, 120); --darkreader-inline-color: #7dffe8;" data-darkreader-inline-color="">#</span><span style="color: rgb(0, 145, 120); --darkreader-inline-color: #7dffe8;" data-darkreader-inline-color="">국가장학금 누가 받을 수 있을까?</span></b></span></p>
<p></p><figure class="imageblock alignRight" data-ke-mobilestyle="widthOrigin" data-filename="3.jpg" data-origin-width="1080" data-origin-height="1080"><span data-url="https://blog.kakaocdn.net/dn/o1nRv/btsHQKGUBUn/cg5o1EOcUAGCnd1RpWJzP1/img.jpg" data-phocus="phocus"><img src="https://blog.kakaocdn.net/dn/o1nRv/btsHQKGUBUn/cg5o1EOcUAGCnd1RpWJzP1/img.jpg" srcset="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&amp;fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fo1nRv%2FbtsHQKGUBUn%2Fcg5o1EOcUAGCnd1RpWJzP1%2Fimg.jpg" onerror="this.onerror=null; this.src='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png'; this.srcset='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png';" data-filename="3.jpg" data-origin-width="1080" data-origin-height="1080" data-phocus-index="2"></span></figure>
<p></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';">우리나라 국・공립대학교의 평균 등록금은 2024년 기준 약 420만 원에 이르고, 사립대 의대의 경우 평균 약 1천만 원, 예체능 계열은 평균 780만 원 이상이라고 합니다<span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">[출처: 교육부, 2024년 4월 대학정보공시 분석 결과 발표(2024)]</span>. 갈수록 상승하는 대학 등록금은 부모님은 물론 대학생 본인에게도 커다란 부담이 될 수밖에 없습니다. 이러한 부담을 줄여주고자 교육부와 한국장학재단에서는 등록금을 지원하는 국가장학금 제도를 시행하고 있습니다. 그렇다면 누가 혜택을 받을 수 있을까요?</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="color: rgb(0, 0, 0); font-family: &quot;Noto Sans KR&quot;; --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">국가장학금은 크게 두 가지 유형으로 구분해 지원합니다. 첫 번째 I 유형은 학생직접지원형이고 두 번째 II 유형은 대학연계지원형입니다. 이 중에서 국가장학금 <b>I 유형(학생직접지원형)</b>은 <b>대한민국 국민</b>으로 <b>국내 대학</b>에 재학 중인 <b>학자금 지원 8구간 이하 대학생</b> 중에서도 <b>성적 기준을 충족</b>하면 지원 구간에 따라 차등 지원합니다.</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p></p><figure class="imageblock alignRight" data-ke-mobilestyle="widthOrigin" data-filename="4.jpg" data-origin-width="1080" data-origin-height="1080"><span data-url="https://blog.kakaocdn.net/dn/N8Dpf/btsHPh68xF9/tQ32SH7JE2QBMoNfdKK2E0/img.jpg" data-phocus="phocus"><img src="https://blog.kakaocdn.net/dn/N8Dpf/btsHPh68xF9/tQ32SH7JE2QBMoNfdKK2E0/img.jpg" srcset="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&amp;fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FN8Dpf%2FbtsHPh68xF9%2FtQ32SH7JE2QBMoNfdKK2E0%2Fimg.jpg" onerror="this.onerror=null; this.src='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png'; this.srcset='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png';" data-filename="4.jpg" data-origin-width="1080" data-origin-height="1080" data-phocus-index="3"></span></figure>
<p></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';"><b><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">2024</span><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">학년도부터</span></b><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color=""> <b>기초</b></span><b><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">・</span><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">차상위 계층의 자녀에게는 등록금 전액이 지원</span></b><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">됩니다. 그 외에는 가구원 소득, 재산, 금융자산, 부채 등을 반영하여 산정한 소득인정액에 따라 지원 구간을 나누고, 구간별로 최대 지원 금액이 달라집니다. 1구간에서 3구간까지는 연간 최대 570만 원, 4구간에서 6구간은 420만 원, 7~8구간은 350만 원입니다.</span></span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';"><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">국가장학금을 받기 위해서는 성적 기준도 충족해야 합니다. <b>직전 학기 12학점을 이수</b>하고<b> 100점 만점 기준 80점 이상</b>을 취득해야 하며, <b>기초</b></span><b><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">・</span><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">차상위 계층</span></b><span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">은 <b>100점 만점 70점 이상</b> 취득해야 합니다. 단, <b>신입생, 편입생, 재입학생</b>의 경우 <b>첫 학기에 한해 성적 기준에서 적용이 제외</b>됩니다. 또한 보호아동을 포함한 <b>자립준비청년</b>은 이수학점 기준은 충족해야 하되 <b>백분위 점수 기준 미적용</b> 대상입니다.</span></span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';"><b><span style="color: rgb(0, 145, 120); --darkreader-inline-color: #7dffe8;" data-darkreader-inline-color="">#</span><span style="color: rgb(0, 145, 120); --darkreader-inline-color: #7dffe8;" data-darkreader-inline-color="">국가장학금 어디에서 신청하면 되나요?</span></b></span></p>
<p></p><figure class="imageblock alignRight" data-ke-mobilestyle="widthOrigin" data-filename="5.jpg" data-origin-width="1080" data-origin-height="1080"><span data-url="https://blog.kakaocdn.net/dn/bnM08P/btsHPqwdFTs/I1ShxOau51spkD8YY6yVMk/img.jpg" data-phocus="phocus"><img src="https://blog.kakaocdn.net/dn/bnM08P/btsHPqwdFTs/I1ShxOau51spkD8YY6yVMk/img.jpg" srcset="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&amp;fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbnM08P%2FbtsHPqwdFTs%2FI1ShxOau51spkD8YY6yVMk%2Fimg.jpg" onerror="this.onerror=null; this.src='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png'; this.srcset='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png';" data-filename="5.jpg" data-origin-width="1080" data-origin-height="1080" data-phocus-index="4"></span></figure>
<p></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';">국가장학금은 <b><a href="http://www.kosaf.go.kr" target="_blank" rel="noopener">한국장학재단 누리집</a> </b>또는<b> 모바일 앱</b>을 통해 <b>반드시 학생 본인이 직접 신청</b>해야 합니다. 신청 기간에는 24시간 신청이 가능하지만 마지막 날인 <b>6월 20일</b>은 <b>18시까지</b>만 신청 가능하니 꼭 마감 시간 전에 접수하시기를 바랍니다.</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';">국가장학금 <span style="color: rgb(0, 0, 0); --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">신청 시 학생 본인은 물론 부모 또는 배우자의 <b>가구원 정보 제공 동의</b>가 필요합니다. 동의 절차는<b> 공동인증서, 금융인증서 </b>또는 <b>하나인증서</b>를 포함한 <b>간편인증 </b>등<b> 전자서명수단</b>을 사용할 수 있습니다. 만약 입력한 가족 정보가 공적 정보와 다를 경우엔 주민등록등본과 가족관계증명서도 함께 제출해야 하므로 사전에 정보가 맞는지 확인하시고 신청하시는 것이 좋습니다. 국가장학금 관련 문의는 한국장학재단 누리집 또는 상담 센터(1599-2000), 한국장학재단 지역센터 및 청년창업센터에서 가능합니다.</span></span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';"><b><span style="color: rgb(0, 145, 120); --darkreader-inline-color: #7dffe8;" data-darkreader-inline-color="">#</span><span style="color: rgb(0, 145, 120); --darkreader-inline-color: #7dffe8;" data-darkreader-inline-color="">신청 결과는 언제 알 수 있을까?</span></b></span></p>
<p></p><figure class="imageblock alignRight" data-ke-mobilestyle="widthOrigin" data-filename="6.jpg" data-origin-width="1080" data-origin-height="1080"><span data-url="https://blog.kakaocdn.net/dn/bQg1jT/btsHQJnJiL7/2VIu3F0HKalNkzV0ah1D1k/img.jpg" data-phocus="phocus"><img src="https://blog.kakaocdn.net/dn/bQg1jT/btsHQJnJiL7/2VIu3F0HKalNkzV0ah1D1k/img.jpg" srcset="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&amp;fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbQg1jT%2FbtsHQJnJiL7%2F2VIu3F0HKalNkzV0ah1D1k%2Fimg.jpg" onerror="this.onerror=null; this.src='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png'; this.srcset='//t1.daumcdn.net/tistory_admin/static/images/no-image-v1.png';" data-filename="6.jpg" data-origin-width="1080" data-origin-height="1080" data-phocus-index="5"></span></figure>
<p></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="color: rgb(0, 0, 0); font-family: &quot;Noto Sans KR&quot;; --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">국가장학금 신청 및 가구원 동의까지 완료되면 학자금 지원 구간 산정을 위해 소득정보 확인이 이루어집니다. 학자금 지원 구간이 산정되면 한국장학재단과 대학에서 약 2주간 신청자 정보 확인 및 심사를 진행합니다. 심사가 종료되고 최종 수혜자가 확정되면 <b>9월 중순</b>부터 대학별로 장학금 지급이 시행됩니다.</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16">&nbsp;</p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="color: rgb(0, 0, 0); font-family: &quot;Noto Sans KR&quot;; --darkreader-inline-color: #ffffff;" data-darkreader-inline-color="">하지만 장학금 수령 후에 <b>자퇴나 제적, 휴학과 같은 학적 변동</b>이 있게 되면 <b>장학금을 반환</b>해야 합니다. 또 중복으로 지원받았을 경우에도 장학금을 반환해야 하므로 부정으로 수급하지 않도록 유의해야 합니다.</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';">&nbsp;</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';"><b><span style="color: rgb(0, 178, 177); --darkreader-inline-color: #5ffffe;" data-darkreader-inline-color="">지금까지 하나은행 블로그와 함께 대학생이라면 주목해야 하는 2학기 국가장학금 신청하기에 관해 알아보았습니다. </span></b></span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';">&nbsp;</span></p>
<p style="font-size: 1.12em; text-align: justify;" data-ke-size="size16"><span style="font-family: 'Noto Sans KR';">그간 대학 등록금이 부담되었던 학생 또는 부모라면 2학기 국가장학금 신청을 통해 학업을 지속할 수 있는 기회를 만들어 보세요. 더 나은 내일을 위한 발돋움의 기회가 되실 겁니다.</span></p></div>`,
};

export const KnowledgeDetail = () => {
  return (
    <div>
      <TopBar title="재테크 꿀팁" back />
      <div className="mx-3">
        <div className="my-5 flex flex-col gap-2 border-b-2 border-hanaGray2 pb-2">
          <p className="font-semibold text-2xl">{detailContent.title}</p>
          <p>by 하나은행 {detailContent.date}</p>
        </div>

        <div
          dangerouslySetInnerHTML={{ __html: detailContent.content }}
          className="mb-8"
        />
      </div>
    </div>
  );
};
