name: 프로젝트 배포

on:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: 환경변수 넣기
        run: |
          touch .env
        working-directory: .
      - name: node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: 의존성 설치
        run: yarn install
      - name: vite 빌드
        run: yarn vite build
      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2
      - name: Docker Hub에 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
      - name: Docker 이미지 빌드 및 Docker Hub에 푸시 (tag)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/theyounghana-frontend:${{ github.sha }}
      - name: Docker 이미지 디제스트 값 출력
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Docker 이미지 빌드 및 Docker Hub에 푸시 (latest)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/theyounghana-frontend:latest
      - name: 어플리케이션 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker stop theyounghana-frontend
            sudo docker rm theyounghana-frontend
            sudo docker image prune -a -f
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/theyounghana-frontend:latest
            sudo docker run -p ${{ secrets.SERVER_PORT }}:80 \
              --name theyounghana-frontend \
              -d ${{ secrets.DOCKER_HUB_USERNAME }}/theyounghana-frontend
